non_concrete_words = ["de","white","black","red","help","green", "scene"
    "right", "while", "left", "use", "ensure", "need", "setting", "information", "risk",
    "name", "take", "type", "business", "location", "lead", "before", "focus", "stop",
    "result", "company", "size", "guide", "distance", "style", "after", "form", "appearance",
    "fitness", "point", "conclusion", "share", "class", "comfort", "care", "language",
    "maintenance", "security", "storage", "look", "start", "list", "path", "protection",
    "element", "choice", "message", "touch", "state", "change", "customer", "plan",
    "structure", "connection", "feature", "spot", "wind", "diet", "love", "flow", "property",
    "serving", "program", "page", "network", "technique", "motion", "turn", "cost", "row",
    "beauty", "cut", "lighting", "music", "taste", "pose", "country", "direction",
    "condition", "gaming", "mind", "presentation", "idea", "story", "material", "job",
    "year", "call", "cleaning", "character", "construction", "hope", "walk", "mix", "install",
    "term", "challenge", "attire", "birthday", "collection", "reflection", "commercial",
    "goal", "brand", "today", "section", "update", "signal", "mobile", "click", "texture",
    "throw", "trip", "grip", "mode", "portion", "price", "pass", "goods", "days", "protein",
    "review", "drinking", "fit", "testing", "index", "force", "express", "race", "none",
    "vitamin", "foreground", "student", "accuracy", "routine", "dinner", "tag", "effect",
    "meter", "core", "decoration", "ease", "placement", "outfit", "supply", "friend",
    "treatment", "capacity", "audio", "week", "record", "root", "mark", "trade", "harm",
    "strike", "contents", "budget", "release", "formation", "passion", "depth", "officer",
    "bank", "payment", "stream", "trail", "aid", "unit", "insert", "figure", "creation",
    "freedom", "talk", "opening", "morning", "consistency", "buttons", "spring", "ad",
    "extension", "neighborhood", "peace", "degree", "moisture", "summer", "fear",
    "heritage", "tradition", "bacteria", "generation", "resistance", "warning", "deal",
    "lots", "pitching", "identification", "conference", "execution", "rolling", "workout",
    "insulation", "beginning", "festival", "mass", "dust", "magic", "garbage", "minute",
    "zero", "medicine", "lay", "dream", "lap", "curve", "lesson", "category", "entrance",
    "tasting", "comparison", "farming", "trigger", "trim", "gesture", "momentum",
    "illustration", "modeling", "fatigue", "disposal", "luxury", "ceremony", "phase",
    "mechanism", "thanks", "essence", "coverage", "battle", "attachment", "kit",
    "instruction", "repeat", "mess", "mesh", "charging", "tension", "blind", "ingredient",
    "procedure", "delta", "twist", "assembly", "removal", "rendering", "starter", "quote",
    "calculator", "indicator", "orientation", "retention", "crisis", "episode", "rendering",
    "a", "s", "c", "b", "y", "e", "d", "m", "o", "l", "n", "g", "f", "r", "k", "v", "x",
    "z", "seven", "th", "third", "min", "zero",
    "green", "scene", "space", "yellow", "color", "work", "number", "body",
    "red", "yellow",  "color", "work", "number", "body",
    "right", "blue", "system", "access", "variety", "level", "quality", "pink", "silver", "second",
    "life", "weather", "world", "position", "science", "order", "colors", "check", "movement",
    "application", "ways", "description", "volume", "news", "sale", "angle", "channel", "cancer",
    "advertisement", "tech", "transfer", "purpose", "sport", "team", "running", "winter", "shadow",
    "medium", "rest", "solid", "installation", "smile", "turns", "exit", "width", "raising", "sample",
    "graphic", "installation", "thing", "carbon", "stripe", "algorithm", "installation", "shadow",
    "medium", "king", "raising", "fill", "rescue", "fix", "spark", "heating", "hearing"
] + [
    "to", "new", "this", "loading", "next", "pursuit", "son", "inch",
    "eleven", "butt", "halves", "push", "press", "cooler", "arena",
    "present", "recording", "wash", "washing", "underside", "paste",
    "factory", "protector", "bill", "pro", "connector", "plug", "blow",
    "ram", "doctor", "ruler", "polish", "hack", "dark", "pit", "shoelace",
    "measuring", "vet", "whites", "jack", "conditioner", "thread",
    "gym", "mason", "toner", "ping", "dummy", "tap", "fuse", "wrap", "knot",
    "processor", "bandage", "extinguisher", "wrap", "lab"
]

non_objects = ["the", "a", "and", "to", "of", "in", "is", "on", "or", "for", "yes", "no",
    "with", "are", "that", "as", "be", "can", "it", "s", "this", "their", "an",
    "you", "by", "from", "they", "there", "which", "such", "other", "also", "your",
    "at", "have", "right", "while", "could", "left", "more", "may", "these", "might",
    "one", "some", "not", "has", "i", "two", "them", "use", "its", "if", "like",
    "using", "various", "time", "several", "help", "well", "being", "overall",
    "large", "up", "make", "will", "when", "provide", "create", "where", "during",
    "used", "each", "near", "should", "any", "different", "additionally",
    "experience", "her", "presence", "making", "small", "about", "sitting",
    "safety", "data", "both", "field", "top", "he", "potential", "around", "we",
    "including", "into", "likely", "but", "ensure", "include", "new", "out", "seen",
    "work", "maintain", "would", "conditions", "example", "control", "was", "high",
    "suggests", "multiple", "information", "part", "skills", "back", "way",
    "providing", "set", "long", "close", "walking", "number", "many", "function",
    "players", "she", "public", "provides", "system", "name", "allows", "take",
    "behind", "enjoying", "meal", "do", "taking", "been", "so", "life", "process",
    "due", "first", "enjoy", "access", "what", "good", "physical", "my", "team",
    "without", "user", "within", "play", "type", "helps", "personal", "creating",
    "further", "even", "main", "safe", "our", "individuals", "typically", "balance",
    "flying", "located", "travel", "bottom", "only", "comfortable", "proper",
    "than", "performance", "serve", "along", "support", "value", "lead", "made",
    "looking", "get", "contribute", "before", "sure", "reasons", "case", "present",
    "off", "keep", "most", "better", "few", "focus", "world", "outdoor", "level",
    "impact", "maintaining", "needs", "just", "then", "role", "find", "ensuring",
    "challenges", "stop", "add", "key", "crucial", "family", "nearby", "having",
    "potentially", "quality", "attention", "following", "avoid", "clear", "users",
    "display", "shows", "especially", "designed", "consider", "learning",
    "development", "content", "return", "working", "under", "additional",
    "behavior", "result", "offer", "adding", "allowing", "combination", "types",
    "indicating", "must", "company", "management", "across", "see", "prevent",
    "indicates", "power", "view", "style", "options", "source", "either", "history",
    "fun", "surface", "form", "context", "appearance", "adds", "community", "those",
    "communication", "let", "necessary", "energy", "events", "found", "photo",
    "customers", "import", "watching", "point", "someone", "visual",
    "understanding", "summary", "engage", "des", "simply", "us", "particularly",
    "require", "care", "enhance", "less", "language", "know", "positive", "serves",
    "moment", "challenging", "science", "steps", "follow", "security", "protect",
    "interaction", "easy", "associated", "start", "training", "short", "order",
    "look", "effectively", "reach", "visibility", "furthermore", "increase", "test",
    "const", "low", "entertainment", "handle", "limited", "given", "preferences",
    "closer", "importance", "interest", "action", "engaged", "getting",
    "protection", "situation", "current", "element", "damage", "understand",
    "leading", "still", "regular", "choice", "changes", "choose", "monitor",
    "message", "since", "tools", "check", "touch", "ready", "minimize", "stand",
    "values", "increased", "growth", "free", "build", "state", "makes", "image","area",
    "scene","environment","presence","two","time",
] + [
    "atmosphere", "space", "setting", "experience", "safety", "activity", "side", "field", 
    "one", "group", "sense", "risk", "event", "variety", "weather", "surroundings", 
    "location", "attention", "balance", "day", "control", "presence", "time", "environment", 
    "scene", "combination", "health", "being", "appearance", "well", "addition", "use", 
    "role", "nature", "purpose", "conclusion", "skill", "reason", "comfort", "focus", 
    "moment", "level", "behavior"
]